### ISSUE TITLE
Out of service in 2023

### ISSUE THREAD

**Issue by Klyuchtxc** [PixelRick/HZD_PC_Gamer_Camera#6]
As far as I understand, after installing the fix, nothing changed. Perhaps I'm missing something? But I just replaced the files in the original folder.

**Comment by PixelRick** [comment]
Hi, the correct way is in the "how-to": Run the game, then the exe (maybe in admin mode since it patches the game at runtime).
I don't know if it still works but it probably does.

**Comment by csisy-bt4w** [comment]
It works, at least with the Epic store version!

Compiled it for myself (not a big fan of downloading "random" executables). Had to drop the wchar thing and use `str*` functions instead (probably a compiler settings issue).

I have no idea how you found what to patch, but the game is so much better with this. Big thanks! :)

**Comment by PixelRick** [comment]
All good then :)

That's why I give sources, but some ppl don't know how to compile and just trust me with it.

I started reverse engineering tasks at 15 and now I'm 34, that's how I found what to patch :)
IDA on one side, and CE + game on the other side to see what was writting/reading camera position and angle.
There is a bit of explanation in the readme as to how the game camera seems to be implemented.

Enjoy your playthrough, it is indeed way better for PC gamers ^^
